name: Deploy to VPS Development

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy via SSH to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /root/srv1097127/development/app_logger/live
            git fetch origin dev
            git reset --hard origin/dev
            source venv/bin/activate
            pip install -r requirements.txt
            echo "--- Running database migrations ---"
            flask db upgrade
            sudo systemctl restart gunicorn.service
          EOF
